apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: securevibe

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: securevibe
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/securevibe/securevibe
    newTag: latest

replicas:
  - name: securevibe
    count: 3