apiVersion: v2
name: securevibe
description: SecureVibe Authentication Platform - Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - authentication
  - auth
  - security
  - jwt
  - oauth
maintainers:
  - name: SecureVibe Team
    email: team@securevibe.io
home: https://securevibe.io
sources:
  - https://github.com/securevibe/securevibe
icon: https://securevibe.io/logo.png